### ISSUE TITLE
trying pyRTOS

### ISSUE THREAD

**Issue by durapensa** [Rybec/pyRTOS#1]
Not an issue, just here to say great project! I currently use https://github.com/cognitivegears/CircuitPython_uschedule and would like to make my blocking code (batches of slow I2C communications mostly) more granular. I will give pyRTOS a try.

**Comment by Rybec** [comment]
Let me know how it goes!  The only CircuitPython devices I have right now are the Rotary Trinkey and the NeoKey Trinkey, and neither have a lot going on.  I am waiting for the RP 2040 Trinkey to do some serious testing, and I would love to add blocking I/O mechanisms for things like I2C.

You should be able to write your own blocking conditions for I2C, but once I have hardware with broader capabilities, I'll see if I can add that to pyRTOS.

**Comment by Rybec** [comment]
I hope this is working for you!  I am now closing this issue, since I am approaching a new major release soon, and I would like to have as few remaining issues as possible.
